// <auto-generated />
using System;
using Hw17.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hw17.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251031114245_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hw17.Models.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "ریچارد آزمن",
                            CategoryId = 1,
                            ImageUrl = "/Images/Books/The_Thursday_Murder_Club.jpg",
                            Price = 300000,
                            PublishedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "باشگاه قتل پنجشنبه"
                        },
                        new
                        {
                            Id = 2,
                            Author = "باربارا تاکمن",
                            CategoryId = 2,
                            ImageUrl = "/Images/Books/The_Guns_of_August.jpg",
                            Price = 250000,
                            PublishedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "توپ های ماه اوت"
                        },
                        new
                        {
                            Id = 3,
                            Author = "اف اسکات فیتزجرالد",
                            CategoryId = 3,
                            ImageUrl = "/Images/Books/The_Great_Gatsby.jpg",
                            Price = 350000,
                            PublishedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "گتسبی بزرگ"
                        },
                        new
                        {
                            Id = 4,
                            Author = "چارلز داروین",
                            CategoryId = 4,
                            ImageUrl = "/Images/Books/On_the_Origin_of_Species.jpg",
                            Price = 200000,
                            PublishedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "منشاء انواع"
                        },
                        new
                        {
                            Id = 5,
                            Author = "فرانک هربرت",
                            CategoryId = 5,
                            ImageUrl = "/Images/Books/Dune.jpg",
                            Price = 230000,
                            PublishedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "تلماسه"
                        },
                        new
                        {
                            Id = 6,
                            Author = "هارپر لی",
                            CategoryId = 6,
                            ImageUrl = "/Images/Books/To_Kill_a_Mockingbird.jpg",
                            Price = 300000,
                            PublishedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "کشتن مرغ مقلد"
                        });
                });

            modelBuilder.Entity("Hw17.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/Images/Categories/crime.png",
                            Name = "جنایی"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/Images/Categories/history.png",
                            Name = "تاریخی"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/Images/Categories/fiction.png",
                            Name = "تخیلی"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/Images/Categories/science.png",
                            Name = "علمی"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/Images/Categories/sci-fi.png",
                            Name = "علمی تخیلی"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/Images/Categories/Novel.png",
                            Name = "رمان"
                        });
                });

            modelBuilder.Entity("Hw17.Models.Entities.Book", b =>
                {
                    b.HasOne("Hw17.Models.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Hw17.Models.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
